[rospy.client][INFO] 2012-12-15 18:09:24,246: init_node, name[/depth_detection], pid[21358]
[xmlrpc][INFO] 2012-12-15 18:09:24,247: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 18:09:24,247: Started XML-RPC server [http://pc:60192/]
[rospy.impl.masterslave][INFO] 2012-12-15 18:09:24,247: _ready: http://pc:60192/
[rospy.registration][INFO] 2012-12-15 18:09:24,248: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2012-12-15 18:09:24,248: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2012-12-15 18:09:24,249: ROS Slave URI: [http://pc:60192/]
[rospy.init][INFO] 2012-12-15 18:09:24,249: registered with master
[rospy.rosout][INFO] 2012-12-15 18:09:24,282: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 18:09:24,284: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 18:09:24,286: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 18:09:36,860: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x38eda28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:09:37,657: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x38eda28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:09:38,877: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x38eda28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rospy.core][INFO] 2012-12-15 18:09:39,873: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 18:09:39,880: signal-2
[rospy.topics][WARNING] 2012-12-15 18:09:39,962: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x38eda28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rospy.core][INFO] 2012-12-15 18:09:40,044: signal_shutdown [atexit]
