[rospy.client][INFO] 2012-12-15 16:04:42,989: init_node, name[/depth_detection], pid[8553]
[xmlrpc][INFO] 2012-12-15 16:04:42,990: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 16:04:42,990: Started XML-RPC server [http://pc:46895/]
[rospy.impl.masterslave][INFO] 2012-12-15 16:04:42,990: _ready: http://pc:46895/
[rospy.init][INFO] 2012-12-15 16:04:42,991: ROS Slave URI: [http://pc:46895/]
[xmlrpc][INFO] 2012-12-15 16:04:42,991: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 16:04:42,992: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 16:04:43,092: registered with master
[rospy.rosout][INFO] 2012-12-15 16:04:43,123: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 16:04:43,126: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 16:04:43,128: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 16:04:55,832: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,015: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,133: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,286: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,487: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,652: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:56,799: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:57,004: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:57,139: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:57,318: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:57,481: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rosout][ERROR] 2012-12-15 16:04:57,664: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2027a70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 108, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 131, in find_close_conts
    if dist(c_i[0], c_j[0]) < MIN_DIST:
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 125, in dist
    d2 = p1[1] - p2[1]
IndexError: index out of bounds

[rospy.core][INFO] 2012-12-15 16:04:57,700: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 16:04:57,705: signal-2
[rospy.core][INFO] 2012-12-15 16:04:57,813: signal_shutdown [atexit]
