[rospy.client][INFO] 2012-12-15 16:57:24,507: init_node, name[/depth_detection], pid[14546]
[xmlrpc][INFO] 2012-12-15 16:57:24,508: XML-RPC server binding to 0.0.0.0
[rospy.init][INFO] 2012-12-15 16:57:24,508: ROS Slave URI: [http://pc:49540/]
[xmlrpc][INFO] 2012-12-15 16:57:24,508: Started XML-RPC server [http://pc:49540/]
[rospy.impl.masterslave][INFO] 2012-12-15 16:57:24,508: _ready: http://pc:49540/
[rospy.registration][INFO] 2012-12-15 16:57:24,509: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2012-12-15 16:57:24,509: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2012-12-15 16:57:24,609: registered with master
[rospy.rosout][INFO] 2012-12-15 16:57:24,641: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 16:57:24,644: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 16:57:24,646: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 16:57:32,906: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:32,936: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:32,993: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,026: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,054: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,086: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,120: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,154: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,185: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,223: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,254: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,282: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,323: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,353: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,384: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,417: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,450: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,481: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,518: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,554: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,594: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,631: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,668: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,704: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,735: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,766: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,798: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,832: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,863: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,895: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,954: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:33,987: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,022: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,055: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,085: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,121: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,151: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,190: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,223: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,274: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,307: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,364: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,397: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:57:34,440: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:57:34,466: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 16:57:34,477: signal-2
[rospy.topics][WARNING] 2012-12-15 16:57:34,489: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x36ceab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:57:34,591: signal_shutdown [atexit]
