[rospy.client][INFO] 2012-12-15 16:56:31,673: init_node, name[/depth_detection], pid[13309]
[xmlrpc][INFO] 2012-12-15 16:56:31,673: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 16:56:31,674: Started XML-RPC server [http://pc:59057/]
[rospy.init][INFO] 2012-12-15 16:56:31,674: ROS Slave URI: [http://pc:59057/]
[rospy.impl.masterslave][INFO] 2012-12-15 16:56:31,674: _ready: http://pc:59057/
[xmlrpc][INFO] 2012-12-15 16:56:31,674: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 16:56:31,675: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 16:56:31,774: registered with master
[rospy.rosout][INFO] 2012-12-15 16:56:31,811: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 16:56:31,814: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 16:56:31,815: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 16:56:42,963: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,005: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,035: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,066: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,106: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,146: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,177: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,207: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,239: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,267: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,298: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,325: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,355: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,383: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,414: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,448: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,483: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,512: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,543: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,582: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,624: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,657: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,689: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,730: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,761: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,794: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,825: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,857: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,887: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,920: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:43,966: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,003: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,043: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,074: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,105: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,142: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,189: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,220: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,251: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,282: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,313: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,354: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,385: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,415: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,447: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,492: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,551: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,592: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,639: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,676: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,707: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,746: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,784: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,814: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,847: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,882: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,933: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:44,965: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,012: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,044: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,077: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,106: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,136: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,168: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,211: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,262: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,292: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,324: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,352: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,386: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,414: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,444: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,473: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,503: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:56:45,533: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:56:45,547: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 16:56:45,567: signal-2
[rospy.topics][WARNING] 2012-12-15 16:56:45,584: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x34b9ab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 158, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 144, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:56:45,681: signal_shutdown [atexit]
