[rospy.client][INFO] 2012-12-15 17:20:23,863: init_node, name[/depth_detection], pid[32239]
[xmlrpc][INFO] 2012-12-15 17:20:23,863: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 17:20:23,864: Started XML-RPC server [http://pc:33242/]
[rospy.init][INFO] 2012-12-15 17:20:23,864: ROS Slave URI: [http://pc:33242/]
[rospy.impl.masterslave][INFO] 2012-12-15 17:20:23,864: _ready: http://pc:33242/
[xmlrpc][INFO] 2012-12-15 17:20:23,865: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 17:20:23,865: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 17:20:23,964: registered with master
[rospy.rosout][INFO] 2012-12-15 17:20:24,012: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 17:20:24,015: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 17:20:24,016: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 17:20:35,805: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,834: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,868: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,896: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,926: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,955: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:35,985: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,016: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,045: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,073: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,102: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,131: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,161: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,192: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,219: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,247: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,274: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,316: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,348: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,378: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,408: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,441: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,479: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,509: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,541: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,577: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,606: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,645: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,676: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,711: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,748: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,778: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,806: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,854: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,883: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,912: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,949: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:36,977: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,003: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,042: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,083: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,110: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,138: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,176: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,205: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,243: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,280: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,316: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,347: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,376: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,404: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,451: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,479: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,507: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,548: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,582: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,610: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,641: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,674: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,709: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,750: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,780: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,812: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,841: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,881: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,918: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,946: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:37,975: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,006: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,056: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,086: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,117: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,156: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,199: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,239: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,269: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,296: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,329: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,361: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,391: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,423: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,452: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,481: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,511: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,541: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,580: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,609: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,646: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,675: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,723: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,752: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,779: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,814: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,841: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,878: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,913: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,945: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:38,973: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rosout][ERROR] 2012-12-15 17:20:39,021: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rospy.core][INFO] 2012-12-15 17:20:39,048: signal_shutdown [signal-2]
[rosout][ERROR] 2012-12-15 17:20:39,053: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rospy.impl.masterslave][INFO] 2012-12-15 17:20:39,057: signal-2
[rospy.topics][WARNING] 2012-12-15 17:20:39,090: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x25dca70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 280, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 154, in merge_contours
    i, j, i_pos, j_pos = cls.find_close_conts(cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 126, in find_close_conts
    np.save('cont', np.array(cont))
ValueError: setting an array element with a sequence.

[rospy.core][INFO] 2012-12-15 17:20:39,198: signal_shutdown [atexit]
