[rospy.client][INFO] 2012-12-15 16:58:16,030: init_node, name[/depth_detection], pid[16004]
[xmlrpc][INFO] 2012-12-15 16:58:16,030: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 16:58:16,031: Started XML-RPC server [http://pc:52397/]
[rospy.init][INFO] 2012-12-15 16:58:16,031: ROS Slave URI: [http://pc:52397/]
[rospy.impl.masterslave][INFO] 2012-12-15 16:58:16,031: _ready: http://pc:52397/
[xmlrpc][INFO] 2012-12-15 16:58:16,031: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 16:58:16,032: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 16:58:16,131: registered with master
[rospy.rosout][INFO] 2012-12-15 16:58:16,169: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 16:58:16,173: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 16:58:16,175: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 16:58:27,426: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,459: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,498: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,547: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,580: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,619: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,651: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,703: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,740: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,774: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,809: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,854: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,893: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,934: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:27,978: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,011: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,041: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,071: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,099: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,130: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,158: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,187: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,219: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,248: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,277: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,308: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,340: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,393: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,435: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,464: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,500: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,531: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,568: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,599: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,648: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,680: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,710: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,739: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,770: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,799: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,828: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,859: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,894: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,935: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,965: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:28,999: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:29,061: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 160, in merge_contours
    return cls.merge_contours(new_cont)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rosout][ERROR] 2012-12-15 16:58:29,090: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:58:29,119: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 16:58:29,125: signal-2
[rospy.topics][WARNING] 2012-12-15 16:58:29,126: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x263aab8>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 281, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 159, in merge_contours
    new_cont.append(cls.merge_two_contours(cont, i, j, i_pos, j_pos))
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 145, in merge_two_contours
    return cont[i][::-1] + cont[j]
ValueError: shape mismatch: objects cannot be broadcast to a single shape

[rospy.core][INFO] 2012-12-15 16:58:29,242: signal_shutdown [atexit]
