[rospy.client][INFO] 2012-12-15 18:16:16,813: init_node, name[/depth_detection], pid[26975]
[xmlrpc][INFO] 2012-12-15 18:16:16,814: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 18:16:16,815: Started XML-RPC server [http://pc:52778/]
[rospy.impl.masterslave][INFO] 2012-12-15 18:16:16,815: _ready: http://pc:52778/
[rospy.init][INFO] 2012-12-15 18:16:16,815: ROS Slave URI: [http://pc:52778/]
[xmlrpc][INFO] 2012-12-15 18:16:16,815: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 18:16:16,816: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 18:16:16,916: registered with master
[rospy.rosout][INFO] 2012-12-15 18:16:16,960: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 18:16:16,963: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 18:16:16,965: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 18:16:26,489: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:26,795: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:27,018: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:27,417: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:27,844: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:27,909: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:28,207: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:28,543: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:28,780: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:28,985: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:29,101: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:16:29,398: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2112a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 285, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rospy.core][INFO] 2012-12-15 18:16:29,456: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 18:16:29,462: signal-2
[rospy.core][INFO] 2012-12-15 18:16:29,595: signal_shutdown [atexit]
